#!/usr/bin/env node
'use strict';
/* Downloads the three typefaces the UI uses and writes @font-face rules,
   so the app looks identical offline and does not depend on Google's CDN.
   Runs automatically from the build and run scripts. Needs internet once. */

const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '..', 'src', 'renderer', 'fonts');
const CSS = path.join(OUT, 'fonts.css');

const FAMILIES = [
  { name: 'Archivo',       weights: [500, 600, 700], css: 'Archivo:wght@500;600;700' },
  { name: 'Inter',         weights: [400, 500, 600], css: 'Inter:wght@400;500;600' },
  { name: 'IBM Plex Mono', weights: [400, 500],      css: 'IBM+Plex+Mono:wght@400;500' }
];

// A modern browser UA gets woff2 back, which is what we want.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const slug = s => s.toLowerCase().replace(/\s+/g, '-');

async function run() {
  fs.mkdirSync(OUT, { recursive: true });
  const query = FAMILIES.map(f => 'family=' + f.css).join('&');
  const url = `https://fonts.googleapis.com/css2?${query}&display=swap`;

  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error('font stylesheet request failed: ' + res.status);
  const sheet = await res.text();

  // Pull one latin file per family/weight out of the returned stylesheet.
  const blocks = sheet.split('@font-face').slice(1);
  const wanted = new Map();
  for (const b of blocks) {
    if (!/unicode-range:[^;]*U\+0000/.test(b) && !/latin/i.test(b)) {
      // keep only the latin subset block; Google emits several
    }
    const fam = (b.match(/font-family:\s*['"]([^'"]+)/) || [])[1];
    const wt  = (b.match(/font-weight:\s*(\d+)/) || [])[1];
    const src = (b.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    if (!fam || !wt || !src) continue;
    const key = `${fam}-${wt}`;
    if (!wanted.has(key)) wanted.set(key, { fam, wt, src });
  }

  let css = '/* Generated by scripts/fetch-fonts.js — do not edit by hand. */\n';
  let ok = 0;
  for (const { fam, wt, src } of wanted.values()) {
    const file = `${slug(fam)}-${wt}.woff2`;
    const dest = path.join(OUT, file);
    if (!fs.existsSync(dest)) {
      const r = await fetch(src, { headers: { 'User-Agent': UA } });
      if (!r.ok) { console.warn('  skipped', file); continue; }
      fs.writeFileSync(dest, Buffer.from(await r.arrayBuffer()));
    }
    css += `@font-face{font-family:'${fam}';font-style:normal;font-weight:${wt};` +
           `font-display:swap;src:url('./fonts/${file}') format('woff2');}\n`;
    ok++;
  }
  fs.writeFileSync(CSS, css);
  console.log(`  fonts ready: ${ok} files in src/renderer/fonts`);
}

run().catch(err => {
  console.warn('  could not download fonts:', err.message);
  console.warn('  the app will still run, using system fonts instead.');
  if (!fs.existsSync(CSS)) fs.writeFileSync(CSS, '/* fonts unavailable — system fallback in use */\n');
  process.exit(0);   // never block the build over fonts
});
